name: 🚀 Deploy ERP Backend to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy via SSH to VPS
    runs-on: debian-latest

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v3

      - name: 🚀 Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.VPS_PATH }}
            git pull origin main
            npm install 
            npm run build
            pm2 restart all
